name: pei-nwdaf

include:
  - path: Infra/docker-compose.yml
  - path: Data-Storage/docker-compose.yml
  - path: Policy/docker-compose.yml
  - path: Ingestion-Service/docker-compose.yml
  - path: Data-Processor/docker-compose.yml
  - path: ML/docker-compose.yml
  - path: Decision/docker-compose.yml
  - path: Frontend/docker-compose.yml

services:

  nef-sim:
    profiles:
      - producers

  data-storage:
    depends_on:
      kafka-init-topics:
        condition: service_completed_successfully

  data-ingestion:
    depends_on:
      kafka-init-topics:
        condition: service_completed_successfully

  processor1:
    depends_on:
      kafka-init-topics:
        condition: service_completed_successfully

  mlservice:
    depends_on:
      kafka-init-topics:
        condition: service_completed_successfully

  decision:
    depends_on:
      kafka-init-topics:
        condition: service_completed_successfully
