# This override removes port mappings for production
services:
  kafka-1:
    ports: !reset []
  kafka-2:
    ports: !reset []
  kafka-3:
    ports: !reset []
  influxdb:
    ports: !reset []
  clickhouse:
    ports: !reset []
  data-storage:
    ports: !reset []
  mlservice:
    ports: !reset []
  mlflow:
    ports: !reset []
  policy-api:
    ports: !reset []
  permit:
    ports: !reset []
  frontend:
    ports: !reset []
  # nginx ports are KEPT
  postgres:
    ports: !reset []
  minio:
    ports: !reset []
  processor1:
    ports: !reset []

# vcnt: this will make k3s not reach postgres and company
#networks:
#  internal:
#    internal: true
