name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Copy .env
        run: cp /home/ubuntu/.env.pei-nwdaf $GITHUB_WORKSPACE/.env

      - name: Deploy
        run: make prod-build
